try:
    # NOTE: the `_version.py` file must not be present in the git repository
    #   as it is generated by setuptools at install time
    from ._version import __version__
except ImportError:  # pragma: no cover
    # Local copy or not installed with setuptools
    __version__ = "999"

import earthkit.data as data
import earthkit.geo as geo
import earthkit.meteo as meteo
import earthkit.plots as plots
import earthkit.regrid as regrid
import earthkit.time as time
import earthkit.transforms as transforms

names = ["data", "geo", "meteo", "plots", "regrid", "time", "transforms"]


import importlib
import pkgutil

for component in pkgutil.iter_modules(__path__, __name__ + "."):
    module_name = component.name
    module, alias = module_name.split(".")
    if alias not in names:
        imported_module = importlib.import_module(module_name)
        globals()[alias] = imported_module
