name: legacy-ci

on:
  push:
    branches:
    - main
    - develop
    tags:
    - "*"
  pull_request:
    branches:
    - main
    - develop
  pull_request_target:
    types: [labeled]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  documentation:
    if: ${{ !github.event.pull_request.head.repo.fork && github.event.action != 'labeled' || github.event.label.name == 'approved-for-ci' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha || github.ref }}
    - name: Install Conda environment with Micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: tests/environment-docs-tests.yml
        environment-name: DEVELOP
        channels: conda-forge
        cache-environment: true
        cache-env-key: ubuntu-latest-3.10-no-eccodes
        create-args: >-
          python=3.10
    - name: Install package
      run: |
        python -m pip install --no-deps -e .
    - name: Build documentation
      run: |
        make docs-build
